export const DEPARTMENTS = [
  { name: "Biosciences and Bioengineering", link: null },
  { name: "Chemical Engineering", link:null },
  { name: "Chemistry", link: null },
  { name: "Civil Engineering", link: null },
  { name: "Computer Science & Engineering", link: null },
  { name: "Design", link: null },
  {
    name: "Electronics and Electrical Engineering",
    link: "https://www.iitg.ac.in/eee_rsf/",
  },
  { name: "Humanities and Social Sciences", link: null },
  { name: "Mathematics", link: "https://www.iitg.ac.in/clubs/rsf_math/" },
  { name: "Mechanical Engineering", link: "https://rsfmech.wixsite.com/rsf-me" },
  { name: "Physics", link: "https://www.iitg.ac.in/phy_rsf/" },
  { name: "Centre for Disaster Management and Research (CDMR)", link: null },
  { name: "Centre for Environment", link: null },
  { name: "Center for Indian Knowledge Systems", link: null },
  { name: "Centre for Intelligent Cyber Physical Systems", link: null },
  { name: "Centre for Linguistic Science and Technology", link: null },
  { name: "Centre for Nanotechnology", link: null },
  { name: "Centre for Sustainable Polymers", link: null },
  { name: "School of Agro and Rural Technology", link: null },
  { name: "School of Business", link: null },
  {
    name: "Mehta Family School of Data Science and Artificial Intelligence",
    link: null,
  },
  { name: "School of Energy Science and Engineering", link: null },
  { name: "School of Health Science and Technology", link: null },
];
